### ISSUE TITLE
TBA release date should be later than `now.today()`

### ISSUE THREAD

**Issue by Vinfall** [icue/SteamWishlistCalendar#4]
Now swc would replace q1/2/3/4 with a specific month:
https://github.com/icue/SteamWishlistCalendar/blob/3d39cd82dd6175e8e47ef953a5319ac9c222c628/swc.py#L24-L29

But when the specified month has passed, and the game is still not released, the estimated time would be a past day.

For example, [Betrix](https://store.steampowered.com/app/2007710/) is set to release on "Q3 2023", which would be estimated to Aug 31. However, it's already September now and the estimated date should be postponed to _the end of next month_, i.e. Sep 30.

I tried to add such function here but failed somehow, hence the issue.
https://github.com/icue/SteamWishlistCalendar/blob/3d39cd82dd6175e8e47ef953a5319ac9c222c628/swc.py#L75-L85

**Comment by icue** [comment]
Thanks for reporting the edge case. I believe this is closed now. Let me know otherwise.
